baseURL = "https://bilk-scheme.github.io/"
title = "Bilk Scheme"
languageCode = "en-us"
description = "An R7RS Scheme compiler written in OCaml. Compiles to bytecode, full numeric tower, hygienic macros, 36 SRFIs, LSP, debugger, and profiler."
enableRobotsTXT = true

# Hextra theme via Hugo Modules
[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

# Navigation menu
[[menu.main]]
  name = "Documentation"
  pageRef = "/docs"
  weight = 1

[[menu.main]]
  name = "Guide"
  pageRef = "/docs/guide"
  weight = 2

[[menu.main]]
  name = "Tools"
  pageRef = "/docs/tools"
  weight = 3

[[menu.main]]
  name = "About"
  pageRef = "/about"
  weight = 4

[[menu.main]]
  name = "Search"
  weight = 5
  [menu.main.params]
    type = "search"

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/bilk-scheme/bilk"
  weight = 6
  [menu.main.params]
    icon = "github"

bilk_rev = "76f96a4"

[params.navbar]
  displayTitle = true
  displayLogo = true

  [params.navbar.logo]
    path = "favicon.svg"
    dark = "favicon-dark.svg"
    width = 24
    height = 24

[params.footer]
  displayCopyright = true
  displayPoweredBy = true

[params.editURL]
  enable = true
  base = "https://github.com/bilk-scheme/bilk-scheme-website/edit/main/content"

# SEO
[params.page.seo]
  enableOpenGraph = true
  enableTwitterCards = true
