baseURL = "https://sabjohnso.github.io/wile-website/"
title = "wile"
languageCode = "en-us"

# Hextra theme via Hugo Modules
[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

# Navigation menu
[[menu.main]]
  name = "Documentation"
  pageRef = "/docs"
  weight = 1

[[menu.main]]
  name = "Get Started"
  pageRef = "/docs/getting-started"
  weight = 2

[[menu.main]]
  name = "Search"
  weight = 3
  [menu.main.params]
    type = "search"

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/sabjohnso/wile"
  weight = 4
  [menu.main.params]
    icon = "github"

[params.navbar]
  displayTitle = true
  displayLogo = false

[params.footer]
  displayCopyright = true
  displayPoweredBy = true

[params.editURL]
  enable = true
  base = "https://github.com/sabjohnso/wile-website/edit/main/content"
